apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../legacy
  - ../openshift

images:
  - name: quay.io/minio/csi-node-driver-registrar
    newName: registry.redhat.io/openshift4/ose-csi-node-driver-registrar-rhel8
    digest: sha256:d4c4fa9f857e73ae1aa49b9d6465a594e6a0c5fd72ef405c695f9e574ee290d8

  - name: quay.io/minio/livenessprobe
    newName: registry.redhat.io/openshift4/ose-csi-livenessprobe-rhel8
    digest: sha256:7fbc65be0a6042e02a7d5de622a2941fc13f91edb2657e1884a6aa39c2af37fb

  - name: quay.io/minio/csi-provisioner
    newName: registry.redhat.io/openshift4/ose-csi-external-provisioner-rhel8
    digest: sha256:67c72fd618ad457b58bcef5ed9c08d2418c1d38c3616509f0a310011cf378f27

  - name: quay.io/minio/csi-resizer
    newName: registry.redhat.io/openshift4/ose-csi-external-resizer-rhel8
    digest: sha256:e69858ab415a56d1371c77cf2c55fcd3b62f41bc79b5f45a43746256611180a7
